import React, { createContext, useContext, useState } from "react"

const bestsellerBooks = [
  {
    id: 1,
    title: '채식주의자',
    filterType: 'domestic',
    category: '소설',
    author: '한강',
    publish: '창비',
    url: '/images/book-sample-4.1.png',
    status: 'none',
  },
  {
    id: 2,
    title: '불편한 편의점',
    filterType: 'domestic',
    category: '소설',
    author: '김호연',
    publish: '나무옆의자',
    url: '/images/book-sample-4.2.png',
    status: 'up',
    statusValue: 1,
  },
  {
    id: 3,
    title: '아몬드',
    filterType: 'domestic',
    category: '소설',
    author: '손원평',
    publish: '창비',
    url: '/images/book-sample-4.3.png',
    status: 'new',
  },
  {
    id: 4,
    title: '미드나잇 라이브러리',
    filterType: 'foreign',
    category: '소설',
    author: '매트 헤이그',
    publish: '인플루엔셜',
    url: '/images/book-sample-4.4.png',
    status: 'none',
  },
  {
    id: 5,
    title: '파친코',
    filterType: 'domestic',
    category: '역사소설',
    author: '이민진',
    publish: '인플루엔셜',
    url: '/images/book-sample-4.5.png',
    status: 'up',
    statusValue: 2,
  },
  {
    id: 6,
    title: '나미야 잡화점의 기적',
    filterType: 'foreign',
    category: '소설',
    author: '히가시노 게이고',
    publish: '현대문학',
    url: '/images/book-sample-4.6.png',
    status: 'none',
  },
  {
    id: 7,
    title: '해리 포터와 마법사의 돌',
    filterType: 'foreign',
    category: '판타지',
    author: 'J.K. 롤링',
    publish: '문학수첩',
    url: '/images/book-sample-4.7.png',
    status: 'down',
    statusValue: 1,
  },
  {
    id: 8,
    title: '이토록 공부가 재미있어지는 순간',
    filterType: 'domestic',
    category: '자기계발',
    author: '박성혁',
    publish: '다산3.0',
    url: '/images/book-sample-4.8.png',
    status: 'new',
  },
  {
    id: 9,
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    filterType: 'e-book',
    category: '에세이',
    author: '백세희',
    publish: '흔',
    url: '/images/book-sample-4.9.png',
    status: 'none',
  },
  {
    id: 10,
    title: '공정하다는 착각',
    filterType: 'e-book',
    category: '사회과학',
    author: '마이클 샌델',
    publish: '와이즈베리',
    url: '/images/book-sample-4.0.png',
    status: 'down',
    statusValue: 2,
  },{
    id: 11,
    title: '기분이 태도가 되지 않게',
    filterType: 'domestic',
    category: '자기계발',
    author: '레몬심리',
    publish: '갤리온',
    url: '/images/book-sample-4.1.png',
    status: 'none'
  },
  {
    id: 12,
    title: '돈의 감각',
    filterType: 'domestic',
    category: '경제',
    author: '이명로(상승미소)',
    publish: '비즈니스북스',
    url: '/images/book-sample-4.2.png',
    status: 'down',
    statusValue: 2,
  },
  {
    id: 13,
    title: '읽기 좋은 글을 씁니다',
    filterType: 'domestic',
    category: '글쓰기',
    author: '유지원',
    publish: '윌북',
    url: '/images/book-sample-4.3.png',
    status: 'up',
    statusValue: 3,
  },
  {
    id: 14,
    title: '무례한 사람에게 웃으며 대처하는 법',
    filterType: 'domestic',
    category: '인문',
    author: '정문정',
    publish: '가나출판사',
    url: '/images/book-sample-4.4.png',
    status: 'none'
  },
  {
    id: 15,
    title: '어린이라는 세계',
    filterType: 'domestic',
    category: '사회',
    author: '김소영',
    publish: '사계절',
    url: '/images/book-sample-4.5.png',
    status: 'new'
  },
  {
    id: 16,
    title: '노르웨이의 숲',
    filterType: 'foreign',
    category: '소설',
    author: '무라카미 하루키',
    publish: '문학사상',
    url: '/images/book-sample-4.6.png',
    status: 'none'
  },
  {
    id: 17,
    title: '인간 실격',
    filterType: 'foreign',
    category: '고전',
    author: '다자이 오사무',
    publish: '민음사',
    url: '/images/book-sample-4.7.png',
    status: 'up',
    statusValue: 3,
  },
  {
    id: 18,
    title: '데일 카네기 인간관계론',
    filterType: 'foreign',
    category: '자기계발',
    author: '데일 카네기',
    publish: '현대지성',
    url: '/images/book-sample-4.8.png',
    status: 'down',
    statusValue: 3,
  },
  {
    id: 19,
    title: '호밀밭의 파수꾼',
    filterType: 'foreign',
    category: '고전',
    author: '제롬 데이비드 샐린저',
    publish: '민음사',
    url: '/images/book-sample-4.9.png',
    status: 'none'
  },
  {
    id: 20,
    title: '총, 균, 쇠',
    filterType: 'foreign',
    category: '역사',
    author: '재레드 다이아몬드',
    publish: '문학사상',
    url: '/images/book-sample-4.0.png',
    status: 'none'
  },
  {
    id: 21,
    title: '아주 희미한 빛으로도',
    filterType: 'e-book',
    category: '에세이',
    author: '이슬아',
    publish: '헤븐',
    url: '/images/book-sample-4.1.png',
    status: 'new'
  },
  {
    id: 22,
    title: '그런 일은 아무에게나 일어나지',
    filterType: 'e-book',
    category: '단편집',
    author: '오노 후유미',
    publish: '한스미디어',
    url: '/images/book-sample-4.2.png',
    status: 'none'
  },
  {
    id: 23,
    title: '어쩌면 별들이 너의 슬픔을 가져갈지도 몰라',
    filterType: 'e-book',
    category: '시집',
    author: '김용택',
    publish: '예담',
    url: '/images/book-sample-4.3.png',
    status: 'none'
  },
  {
    id: 24,
    title: '나의 하루는 4시 30분에 시작된다',
    filterType: 'e-book',
    category: '자기계발',
    author: '김유진',
    publish: '토네이도',
    url: '/images/book-sample-4.4.png',
    status: 'up',
    statusValue: 3,
  },
  {
    id: 25,
    title: '나는 나로 살기로 했다',
    filterType: 'e-book',
    category: '인문',
    author: '김수현',
    publish: '마음의숲',
    url: '/images/book-sample-4.5.png',
    status: 'new'
  },{
    id: 26,
    title: '말의 품격',
    filterType: 'e-book',
    category: '인문',
    author: '이기주',
    publish: '황소북스',
    url: '/images/book-sample-4.6.png',
    status: 'down',
    statusValue: 2,
  },
  {
    id: 27,
    title: '멋진 신세계',
    filterType: 'foreign',
    category: '고전소설',
    author: '올더스 헉슬리',
    publish: '소담출판사',
    url: '/images/book-sample-4.7.png',
    status: 'none'
  },
  {
    id: 28,
    title: '하마터면 열심히 살 뻔했다',
    filterType: 'e-book',
    category: '에세이',
    author: '하완',
    publish: '웅진지식하우스',
    url: '/images/book-sample-4.8.png',
    status: 'up',
    statusValue: 1,
  },
  {
    id: 29,
    title: '어떻게 말해줘야 할까',
    filterType: 'e-book',
    category: '육아심리',
    author: '오은영',
    publish: '김영사',
    url: '/images/book-sample-4.9.png',
    status: 'none'
  },
  {
    id: 30,
    title: '모모',
    filterType: 'foreign',
    category: '판타지',
    author: '미하엘 엔데',
    publish: '비룡소',
    url: '/images/book-sample-4.0.png',
    status: 'none'
  }
]

const recommandBooks = [
  {
    id: 1,
    title: '그림자 속의 나',
    filterType: 'domestic',
    category: '심리',
    author: '정유진',
    publish: '마음의숲',
    url: '/images/book-sample-4.1.png',
  },
  {
    id: 2,
    title: '영혼의 물리학',
    filterType: 'foreign',
    category: '과학',
    author: '카를로 로벨리',
    publish: '알마출판사',
    url: '/images/book-sample-4.2.png',
  },
  {
    id: 3,
    title: '너에게 닿는 말',
    filterType: 'e-book',
    category: '에세이',
    author: '이나래',
    publish: '열린책들',
    url: '/images/book-sample-4.3.png',
  },
  {
    id: 4,
    title: '시간의 문',
    filterType: 'domestic',
    category: '판타지',
    author: '윤태진',
    publish: '북폴리오',
    url: '/images/book-sample-4.4.png',
  },
  {
    id: 5,
    title: '의식의 기원',
    filterType: 'foreign',
    category: '철학',
    author: '댄 데닛',
    publish: '사이언스북스',
    url: '/images/book-sample-4.5.png',
  },
  {
    id: 6,
    title: '끝없는 여정',
    filterType: 'e-book',
    category: '여행기',
    author: '조해성',
    publish: '인디펍',
    url: '/images/book-sample-4.6.png',
  },
  {
    id: 7,
    title: '한 사람을 위한 마음',
    filterType: 'domestic',
    category: '에세이',
    author: '박하늘',
    publish: '웅진지식하우스',
    url: '/images/book-sample-4.7.png',
  },
  {
    id: 8,
    title: '플랫폼 제국의 미래',
    filterType: 'foreign',
    category: '경제',
    author: '스콧 갤러웨이',
    publish: '비즈니스북스',
    url: '/images/book-sample-4.8.png',
  },
  {
    id: 9,
    title: '무지개 건너편',
    filterType: 'e-book',
    category: '문학',
    author: '이하진',
    publish: '스토리야',
    url: '/images/book-sample-4.9.png',
  },
  {
    id: 10,
    title: '완벽하지 않아도 좋아',
    filterType: 'domestic',
    category: '자기계발',
    author: '김서윤',
    publish: '더블북',
    url: '/images/book-sample-4.0.png',
  },
  {
    id: 11,
    title: '침묵의 땅',
    filterType: 'foreign',
    category: '환경',
    author: '레이첼 카슨',
    publish: '에코북',
    url: '/images/book-sample-4.1.png',
  },
  {
    id: 12,
    title: '달의 목소리',
    filterType: 'e-book',
    category: 'SF',
    author: '정세호',
    publish: '미래지향',
    url: '/images/book-sample-4.2.png',
  },
  {
    id: 13,
    title: '사람의 온도',
    filterType: 'domestic',
    category: '휴먼드라마',
    author: '이하영',
    publish: '블루버드',
    url: '/images/book-sample-4.3.png',
  },
  {
    id: 14,
    title: '문명의 붕괴',
    filterType: 'foreign',
    category: '역사',
    author: '재레드 다이아몬드',
    publish: '김영사',
    url: '/images/book-sample-4.4.png',
  },
  {
    id: 15,
    title: '괜찮지 않아도 괜찮아',
    filterType: 'e-book',
    category: '심리',
    author: '고다혜',
    publish: '책방유령',
    url: '/images/book-sample-4.5.png',
  },
  {
    id: 16,
    title: '소란한 밤의 기록',
    filterType: 'domestic',
    category: '시',
    author: '이도연',
    publish: '문학동네',
    url: '/images/book-sample-4.6.png',
  },
  {
    id: 17,
    title: '생각의 역사',
    filterType: 'foreign',
    category: '철학',
    author: '윌 듀런트',
    publish: '페이퍼로드',
    url: '/images/book-sample-4.7.png',
  },
  {
    id: 18,
    title: '낮의 빛, 밤의 어둠',
    filterType: 'e-book',
    category: '소설',
    author: '최이수',
    publish: '밤의책',
    url: '/images/book-sample-4.8.png',
  },
  {
    id: 19,
    title: '세상은 연결되어 있다',
    filterType: 'domestic',
    category: '사회',
    author: '노현우',
    publish: '갈라파고스',
    url: '/images/book-sample-4.9.png',
  },
  {
    id: 20,
    title: '진화의 언어',
    filterType: 'foreign',
    category: '과학',
    author: '댄 에버렛',
    publish: '을유문화사',
    url: '/images/book-sample-4.0.png',
  },
  {
    id: 21,
    title: '나는 나를 믿는다',
    filterType: 'e-book',
    category: '자기계발',
    author: '정다운',
    publish: '지혜출판',
    url: '/images/book-sample-4.1.png',
  },
  {
    id: 22,
    title: '지구 끝의 도서관',
    filterType: 'domestic',
    category: '문학',
    author: '백도연',
    publish: '창비',
    url: '/images/book-sample-4.2.png',
  },
  {
    id: 23,
    title: '인간 본성에 대하여',
    filterType: 'foreign',
    category: '심리학',
    author: '스티븐 핑커',
    publish: '사이언스북스',
    url: '/images/book-sample-4.3.png',
  },
  {
    id: 24,
    title: '별빛을 닮은 하루',
    filterType: 'e-book',
    category: '에세이',
    author: '조은하',
    publish: '별책부록',
    url: '/images/book-sample-4.4.png',
  },
  {
    id: 25,
    title: '작은 것들의 신',
    filterType: 'domestic',
    category: '문학',
    author: '김나래',
    publish: '현대문학',
    url: '/images/book-sample-4.5.png',
  },
  {
    id: 26,
    title: '인류의 내일',
    filterType: 'foreign',
    category: '미래학',
    author: '유발 하라리',
    publish: '김영사',
    url: '/images/book-sample-4.6.png',
  },
  {
    id: 27,
    title: '밤이 찾아온다면',
    filterType: 'e-book',
    category: '드라마',
    author: '김리안',
    publish: '이야기출판',
    url: '/images/book-sample-4.7.png',
  },
  {
    id: 28,
    title: '생각의 기술',
    filterType: 'domestic',
    category: '철학',
    author: '정경미',
    publish: '마인드플랜',
    url: '/images/book-sample-4.8.png',
  },
  {
    id: 29,
    title: '디지털 미니멀리즘',
    filterType: 'foreign',
    category: '테크',
    author: '칼 뉴포트',
    publish: '샘앤파커스',
    url: '/images/book-sample-4.9.png',
  },
  {
    id: 30,
    title: '고요함의 힘',
    filterType: 'e-book',
    category: '명상',
    author: '정혜윤',
    publish: '비움출판',
    url: '/images/book-sample-4.0.png',
  }
];


const BARContext = createContext()

export function BARProvider({children}){
  const [selectedBR , setSelectedBR] = useState('B')
  const [selectedCategory , setSelectedCategory] = useState('all')
  return(
    <BARContext.Provider value={{
      bestsellerBooks,recommandBooks,
      selectedBR , setSelectedBR,
      selectedCategory, setSelectedCategory
      }}>
      {children}
    </BARContext.Provider>
  )
}

export function useBARContext(){
  const context = useContext(BARContext)
  if(!context){
    throw new Error('useBARContext Error')
  }
  return context
}